//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Localization.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskTitles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskTitles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization.Tasks.TaskTitles", typeof(TaskTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додавання коментарів до робочого простору.
        /// </summary>
        public static string AddingCommentsToWorkspace {
            get {
                return ResourceManager.GetString("AddingCommentsToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додавання зовнішніх даних до робочого простору.
        /// </summary>
        public static string AddingExternalDataToWorkspace {
            get {
                return ResourceManager.GetString("AddingExternalDataToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластеризація (DBSCAN).
        /// </summary>
        public static string ClusterizationDBSCAN {
            get {
                return ResourceManager.GetString("ClusterizationDBSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластеризація (Gaussian Mixture).
        /// </summary>
        public static string ClusterizationGaussianMixture {
            get {
                return ResourceManager.GetString("ClusterizationGaussianMixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластеризація (k-Means).
        /// </summary>
        public static string ClusterizationKMeans {
            get {
                return ResourceManager.GetString("ClusterizationKMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластеризація (Один кластер).
        /// </summary>
        public static string ClusterizationOneCluser {
            get {
                return ResourceManager.GetString("ClusterizationOneCluser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кластеризація (Spectral Clustering).
        /// </summary>
        public static string ClusterizationSpectralClustering {
            get {
                return ResourceManager.GetString("ClusterizationSpectralClustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження всіх ембедингів з робочого простору.
        /// </summary>
        public static string LoadingAllEmbeddingsInWorkspace {
            get {
                return ResourceManager.GetString("LoadingAllEmbeddingsInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження каналів з платформи Youtube.
        /// </summary>
        public static string LoadingChannelsFromYoutube {
            get {
                return ResourceManager.GetString("LoadingChannelsFromYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження коментарів з платформи Youtube.
        /// </summary>
        public static string LoadingCommentsFromYoutube {
            get {
                return ResourceManager.GetString("LoadingCommentsFromYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження ембедингів з паку.
        /// </summary>
        public static string LoadingEmbeddingsPack {
            get {
                return ResourceManager.GetString("LoadingEmbeddingsPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження повідомлень з платформи Telegram.
        /// </summary>
        public static string LoadingMessagesFromTelegram {
            get {
                return ResourceManager.GetString("LoadingMessagesFromTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження відповідей з платформи Telegram.
        /// </summary>
        public static string LoadingRepliesFromTelegram {
            get {
                return ResourceManager.GetString("LoadingRepliesFromTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заватаження відео з платформи Youtube.
        /// </summary>
        public static string LoadingVideosFromYoutube {
            get {
                return ResourceManager.GetString("LoadingVideosFromYoutube", resourceCulture);
            }
        }
    }
}
