//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Localization.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskTitlesPatterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskTitlesPatterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization.Tasks.TaskTitlesPatterns", typeof(TaskTitlesPatterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding external data to workspace.
        /// </summary>
        internal static string AddingExternalDataToWorkspace {
            get {
                return ResourceManager.GetString("AddingExternalDataToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddingTelegramMessagesToWorkspace.
        /// </summary>
        internal static string AddingTelegramMessagesToWorkspace {
            get {
                return ResourceManager.GetString("AddingTelegramMessagesToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddingTelegramRepliesToWorkspace.
        /// </summary>
        internal static string AddingTelegramRepliesToWorkspace {
            get {
                return ResourceManager.GetString("AddingTelegramRepliesToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddingWorkspace.
        /// </summary>
        internal static string AddingWorkspace {
            get {
                return ResourceManager.GetString("AddingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddingYoutubeCommentsToWorkspace.
        /// </summary>
        internal static string AddingYoutubeCommentsToWorkspace {
            get {
                return ResourceManager.GetString("AddingYoutubeCommentsToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustering.
        /// </summary>
        internal static string Clustering {
            get {
                return ResourceManager.GetString("Clustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationDBSCAN.
        /// </summary>
        internal static string ClusterizationDBSCAN {
            get {
                return ResourceManager.GetString("ClusterizationDBSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationGaussianMixture.
        /// </summary>
        internal static string ClusterizationGaussianMixture {
            get {
                return ResourceManager.GetString("ClusterizationGaussianMixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationKMeans.
        /// </summary>
        internal static string ClusterizationKMeans {
            get {
                return ResourceManager.GetString("ClusterizationKMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationOneCluser.
        /// </summary>
        internal static string ClusterizationOneCluser {
            get {
                return ResourceManager.GetString("ClusterizationOneCluser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationSpectralClustering.
        /// </summary>
        internal static string ClusterizationSpectralClustering {
            get {
                return ResourceManager.GetString("ClusterizationSpectralClustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimensionReduction.
        /// </summary>
        internal static string DimensionReduction {
            get {
                return ResourceManager.GetString("DimensionReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializingWorkspace.
        /// </summary>
        internal static string InitializingWorkspace {
            get {
                return ResourceManager.GetString("InitializingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingAllEmbeddingsInWorkspace.
        /// </summary>
        internal static string LoadingAllEmbeddingsInWorkspace {
            get {
                return ResourceManager.GetString("LoadingAllEmbeddingsInWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingChannelsFromYoutube.
        /// </summary>
        internal static string LoadingChannelsFromYoutube {
            get {
                return ResourceManager.GetString("LoadingChannelsFromYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingCommentsFromYoutube.
        /// </summary>
        internal static string LoadingCommentsFromYoutube {
            get {
                return ResourceManager.GetString("LoadingCommentsFromYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingEmbeddingsPack.
        /// </summary>
        internal static string LoadingEmbeddingsPack {
            get {
                return ResourceManager.GetString("LoadingEmbeddingsPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingExternalDataAndAddingToWorkspace.
        /// </summary>
        internal static string LoadingExternalDataAndAddingToWorkspace {
            get {
                return ResourceManager.GetString("LoadingExternalDataAndAddingToWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingExternalDataObjects.
        /// </summary>
        internal static string LoadingExternalDataObjects {
            get {
                return ResourceManager.GetString("LoadingExternalDataObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingMessagesFromTelegram.
        /// </summary>
        internal static string LoadingMessagesFromTelegram {
            get {
                return ResourceManager.GetString("LoadingMessagesFromTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingRepliesFromTelegram.
        /// </summary>
        internal static string LoadingRepliesFromTelegram {
            get {
                return ResourceManager.GetString("LoadingRepliesFromTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadingVideosFromYoutube.
        /// </summary>
        internal static string LoadingVideosFromYoutube {
            get {
                return ResourceManager.GetString("LoadingVideosFromYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TilesCreating.
        /// </summary>
        internal static string TilesCreating {
            get {
                return ResourceManager.GetString("TilesCreating", resourceCulture);
            }
        }
    }
}
