// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ClusterizationDbContext))]
    [Migration("20240214142729_add-visible-type-and-changing-type")]
    partial class addvisibletypeandchangingtype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClusterClusterizationEntity", b =>
                {
                    b.Property<int>("ClustersId")
                        .HasColumnType("int");

                    b.Property<int>("EntitiesId")
                        .HasColumnType("int");

                    b.HasKey("ClustersId", "EntitiesId");

                    b.HasIndex("EntitiesId");

                    b.ToTable("ClusterClusterizationEntity");
                });

            modelBuilder.Entity("ClusterizationWorkspaceComment", b =>
                {
                    b.Property<string>("CommentsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkspacesId")
                        .HasColumnType("int");

                    b.HasKey("CommentsId", "WorkspacesId");

                    b.HasIndex("WorkspacesId");

                    b.ToTable("ClusterizationWorkspaceComment");
                });

            modelBuilder.Entity("ClusterizationWorkspaceExternalObject", b =>
                {
                    b.Property<string>("ExternalObjectsFullId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkspacesId")
                        .HasColumnType("int");

                    b.HasKey("ExternalObjectsFullId", "WorkspacesId");

                    b.HasIndex("WorkspacesId");

                    b.ToTable("ClusterizationWorkspaceExternalObject");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("ClusterizationAbstractAlgorithms");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ClusterizationAbstactAlgorithm");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.ClusterizationAlgorithmType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClusterizationAlgorithmType");

                    b.HasData(
                        new
                        {
                            Id = "KMeans",
                            Description = "Впорядкування множини об'єктів у порівняно однорідні групи.",
                            Name = "k-means"
                        },
                        new
                        {
                            Id = "OneCluster",
                            Description = "Об'єднання елементів в один кластер",
                            Name = "Один кластер"
                        },
                        new
                        {
                            Id = "DBScan",
                            Description = "Density-Based Spatial Clustering Of Applications With Noise",
                            Name = "DBSCAN"
                        },
                        new
                        {
                            Id = "SpectralClustering",
                            Description = "Cпектральна кластеризація базується на принципах теорії графів і лінійної алгебри",
                            Name = "Spectral Clustering"
                        },
                        new
                        {
                            Id = "GaussianMixture",
                            Description = "Метод кластеризації, який моделює дані як суміш розділів Гауса",
                            Name = "Gaussian Mixture"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentClusterId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentClusterId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationDimensionType", b =>
                {
                    b.Property<int>("DimensionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DimensionCount"));

                    b.HasKey("DimensionCount");

                    b.ToTable("ClusterizationDimensionTypes");

                    b.HasData(
                        new
                        {
                            DimensionCount = 2
                        },
                        new
                        {
                            DimensionCount = 3
                        },
                        new
                        {
                            DimensionCount = 100
                        },
                        new
                        {
                            DimensionCount = 1536
                        });
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmbeddingDataId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalObjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TextValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("EmbeddingDataId");

                    b.HasIndex("ExternalObjectId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ClusterizationEntites");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmId")
                        .HasColumnType("int");

                    b.Property<string>("ChangingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DimensionCount")
                        .HasColumnType("int");

                    b.Property<string>("DimensionalityReductionTechniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCalculated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElected")
                        .HasColumnType("bit");

                    b.Property<int>("MaxTileLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinTileLevel")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VisibleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.HasIndex("DimensionCount");

                    b.HasIndex("DimensionalityReductionTechniqueId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ClusterizationProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("TilesLevelId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TilesLevelId");

                    b.ToTable("ClusterizationTiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTilesLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxXValue")
                        .HasColumnType("float");

                    b.Property<double>("MaxYValue")
                        .HasColumnType("float");

                    b.Property<double>("MinXValue")
                        .HasColumnType("float");

                    b.Property<double>("MinYValue")
                        .HasColumnType("float");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("TileCount")
                        .HasColumnType("int");

                    b.Property<double>("TileLength")
                        .HasColumnType("float");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ClusterizationTilesLevels");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClusterizationTypes");

                    b.HasData(
                        new
                        {
                            Id = "Comments",
                            Name = "Коментарі"
                        },
                        new
                        {
                            Id = "External",
                            Name = "З файлу"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntitiesCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllDataEmbedded")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VisibleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TypeId");

                    b.ToTable("ClusterizationWorkspaces");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspaceDRTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DRTechniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DRTechniqueId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ClusterizationWorkspaceDRTechniques");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.DisplayedPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClusterId")
                        .HasColumnType("int");

                    b.Property<int>("OptimizationLevel")
                        .HasColumnType("int");

                    b.Property<int>("TileId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("TileId");

                    b.ToTable("DisplayedPoints");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Entities.DimensionalityReduction.DimensionalityReductionTechnique", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimensionalityReductionTechniques");

                    b.HasData(
                        new
                        {
                            Id = "PCA",
                            Name = "Principal Component Analysis"
                        },
                        new
                        {
                            Id = "t-SNE",
                            Name = "t-Distributed Stochastic Neighbor Embedding"
                        },
                        new
                        {
                            Id = "JSL",
                            Name = "Johnson-Lindenstrauss lemma"
                        });
                });

            modelBuilder.Entity("Domain.Entities.DimensionalityReduction.DimensionalityReductionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClusterizationEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("ClusterizationWorkspaceDRTechniqueId")
                        .HasColumnType("int");

                    b.Property<int?>("EmbeddingDataId")
                        .HasColumnType("int");

                    b.Property<string>("TechniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterizationEntityId");

                    b.HasIndex("ClusterizationWorkspaceDRTechniqueId");

                    b.HasIndex("EmbeddingDataId")
                        .IsUnique()
                        .HasFilter("[EmbeddingDataId] IS NOT NULL");

                    b.HasIndex("TechniqueId", "ClusterizationWorkspaceDRTechniqueId");

                    b.ToTable("DimensionalityReductionValues");
                });

            modelBuilder.Entity("Domain.Entities.Embeddings.EmbeddingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DimensionalityReductionValueId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalEmbeddingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique()
                        .HasFilter("[CommentId] IS NOT NULL");

                    b.ToTable("EmbeddingDatas");
                });

            modelBuilder.Entity("Domain.Entities.Embeddings.EmbeddingDimensionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DimensionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DimensionalityReductionValueId")
                        .HasColumnType("int");

                    b.Property<int?>("EmbeddingDataId")
                        .HasColumnType("int");

                    b.Property<string>("ValuesString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionTypeId");

                    b.HasIndex("DimensionalityReductionValueId");

                    b.HasIndex("EmbeddingDataId")
                        .IsUnique()
                        .HasFilter("[EmbeddingDataId] IS NOT NULL");

                    b.ToTable("EmbeddingDimensionValues");
                });

            modelBuilder.Entity("Domain.Entities.ExternalData.ExternalObject", b =>
                {
                    b.Property<string>("FullId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmbeddingDataId")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FullId");

                    b.HasIndex("EmbeddingDataId")
                        .IsUnique()
                        .HasFilter("[EmbeddingDataId] IS NOT NULL");

                    b.ToTable("ExternalObjects");
                });

            modelBuilder.Entity("Domain.Entities.Tasks.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Percent")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("MyTasks");
                });

            modelBuilder.Entity("Domain.Entities.Tasks.MyTaskState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyTaskStates");

                    b.HasData(
                        new
                        {
                            Id = "Error",
                            Name = "Помилка"
                        },
                        new
                        {
                            Id = "Wait",
                            Name = "Очікування"
                        },
                        new
                        {
                            Id = "Process",
                            Name = "Виконується"
                        },
                        new
                        {
                            Id = "Completed",
                            Name = "Виконалася"
                        },
                        new
                        {
                            Id = "Stopped",
                            Name = "Призупинено"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChannelImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoadedCommentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoadedVideoCount")
                        .HasColumnType("int");

                    b.Property<string>("LoaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("PublishedAtDateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedAtRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubscriberCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoCount")
                        .HasColumnType("int");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LoaderId");

                    b.HasIndex("PublishedAtDateTimeOffset", "VideoCount", "SubscriberCount");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorChannelUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanReply")
                        .HasColumnType("bit");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmbeddingDataId")
                        .HasColumnType("int");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("PublishedAtDateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedAtRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TotalReplyCount")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("UpdatedAtDateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedAtRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("LoaderId");

                    b.HasIndex("PublishedAtDateTimeOffset");

                    b.HasIndex("VideoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Video", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChannelTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("DefaultAudioLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("LiveBroadcaseContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoadedCommentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("PublishedAtDateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedAtRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("LoaderId");

                    b.HasIndex("PublishedAtDateTimeOffset", "CommentCount", "ViewCount");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.Non_hierarchical.DBScanAlgorithm", b =>
                {
                    b.HasBaseType("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm");

                    b.Property<double>("Epsilon")
                        .HasColumnType("float");

                    b.Property<int>("MinimumPointsPerCluster")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DBScanAlgorithm");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.Non_hierarchical.GaussianMixtureAlgorithm", b =>
                {
                    b.HasBaseType("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm");

                    b.Property<int>("NumberOfComponents")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("GaussianMixtureAlgorithm");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.Non_hierarchical.KMeansAlgorithm", b =>
                {
                    b.HasBaseType("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm");

                    b.Property<int>("NumClusters")
                        .HasColumnType("int");

                    b.Property<int>("Seed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("KMeansAlgorithm");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.Non_hierarchical.OneClusterAlgorithm", b =>
                {
                    b.HasBaseType("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm");

                    b.Property<string>("ClusterColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OneClusterAlgorithm");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.Non_hierarchical.SpectralClusteringAlgorithm", b =>
                {
                    b.HasBaseType("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm");

                    b.Property<double>("Gamma")
                        .HasColumnType("float");

                    b.Property<int>("NumClusters")
                        .HasColumnType("int");

                    b.ToTable("ClusterizationAbstractAlgorithms", t =>
                        {
                            t.Property("NumClusters")
                                .HasColumnName("SpectralClusteringAlgorithm_NumClusters");
                        });

                    b.HasDiscriminator().HasValue("SpectralClusteringAlgorithm");
                });

            modelBuilder.Entity("ClusterClusterizationEntity", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.Cluster", null)
                        .WithMany()
                        .HasForeignKey("ClustersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationEntity", null)
                        .WithMany()
                        .HasForeignKey("EntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClusterizationWorkspaceComment", b =>
                {
                    b.HasOne("Domain.Entities.Youtube.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClusterizationWorkspaceExternalObject", b =>
                {
                    b.HasOne("Domain.Entities.ExternalData.ExternalObject", null)
                        .WithMany()
                        .HasForeignKey("ExternalObjectsFullId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.Algorithms.ClusterizationAlgorithmType", "Type")
                        .WithMany("ClusterizationAlgorithms")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Cluster", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.Cluster", "ParentCluster")
                        .WithMany("ChildClusters")
                        .HasForeignKey("ParentClusterId");

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationProfile", "Profile")
                        .WithMany("Clusters")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCluster");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationEntity", b =>
                {
                    b.HasOne("Domain.Entities.Youtube.Comment", "Comment")
                        .WithMany("ClusterizationEntities")
                        .HasForeignKey("CommentId");

                    b.HasOne("Domain.Entities.Embeddings.EmbeddingData", "EmbeddingData")
                        .WithMany("Entities")
                        .HasForeignKey("EmbeddingDataId");

                    b.HasOne("Domain.Entities.ExternalData.ExternalObject", "ExternalObject")
                        .WithMany("ClusterizationEntities")
                        .HasForeignKey("ExternalObjectId");

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspace", "Workspace")
                        .WithMany("Entities")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("EmbeddingData");

                    b.Navigation("ExternalObject");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationProfile", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm", "Algorithm")
                        .WithMany("Profiles")
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationDimensionType", "DimensionType")
                        .WithMany("Profiles")
                        .HasForeignKey("DimensionCount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DimensionalityReduction.DimensionalityReductionTechnique", "DimensionalityReductionTechnique")
                        .WithMany("Profiles")
                        .HasForeignKey("DimensionalityReductionTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers.Customer", "Owner")
                        .WithMany("Profiles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspace", "Workspace")
                        .WithMany("Profiles")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");

                    b.Navigation("DimensionType");

                    b.Navigation("DimensionalityReductionTechnique");

                    b.Navigation("Owner");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTile", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.ClusterizationTile", "Parent")
                        .WithMany("ChildTiles")
                        .HasForeignKey("ParentId");

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationProfile", "Profile")
                        .WithMany("Tiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationTilesLevel", "TilesLevel")
                        .WithMany("Tiles")
                        .HasForeignKey("TilesLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Profile");

                    b.Navigation("TilesLevel");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTilesLevel", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.ClusterizationProfile", "Profile")
                        .WithMany("TilesLevels")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspace", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Owner")
                        .WithMany("Workspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationType", "Type")
                        .WithMany("Workspaces")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspaceDRTechnique", b =>
                {
                    b.HasOne("Domain.Entities.DimensionalityReduction.DimensionalityReductionTechnique", "DRTechnique")
                        .WithMany("ClusterizationWorkspaceDRTechniques")
                        .HasForeignKey("DRTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspace", "Workspace")
                        .WithMany("ClusterizationWorkspaceDRTechniques")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DRTechnique");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.DisplayedPoint", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.Cluster", "Cluster")
                        .WithMany("DisplayedPoints")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationTile", "Tile")
                        .WithMany("Points")
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("Domain.Entities.DimensionalityReduction.DimensionalityReductionValue", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.ClusterizationEntity", "ClusterizationEntity")
                        .WithMany("DimensionalityReductionValues")
                        .HasForeignKey("ClusterizationEntityId");

                    b.HasOne("Domain.Entities.Clusterization.ClusterizationWorkspaceDRTechnique", "ClusterizationWorkspaceDRTechnique")
                        .WithMany("DRValues")
                        .HasForeignKey("ClusterizationWorkspaceDRTechniqueId");

                    b.HasOne("Domain.Entities.Embeddings.EmbeddingData", "EmbeddingData")
                        .WithOne("DimensionalityReductionValue")
                        .HasForeignKey("Domain.Entities.DimensionalityReduction.DimensionalityReductionValue", "EmbeddingDataId");

                    b.HasOne("Domain.Entities.DimensionalityReduction.DimensionalityReductionTechnique", "Technique")
                        .WithMany("Values")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterizationEntity");

                    b.Navigation("ClusterizationWorkspaceDRTechnique");

                    b.Navigation("EmbeddingData");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("Domain.Entities.Embeddings.EmbeddingData", b =>
                {
                    b.HasOne("Domain.Entities.Youtube.Comment", "Comment")
                        .WithOne("EmbeddingData")
                        .HasForeignKey("Domain.Entities.Embeddings.EmbeddingData", "CommentId");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Domain.Entities.Embeddings.EmbeddingDimensionValue", b =>
                {
                    b.HasOne("Domain.Entities.Clusterization.ClusterizationDimensionType", "DimensionType")
                        .WithMany("DimensionValues")
                        .HasForeignKey("DimensionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DimensionalityReduction.DimensionalityReductionValue", "DimensionalityReductionValue")
                        .WithMany("Embeddings")
                        .HasForeignKey("DimensionalityReductionValueId");

                    b.HasOne("Domain.Entities.Embeddings.EmbeddingData", "EmbeddingData")
                        .WithOne("OriginalEmbedding")
                        .HasForeignKey("Domain.Entities.Embeddings.EmbeddingDimensionValue", "EmbeddingDataId");

                    b.Navigation("DimensionType");

                    b.Navigation("DimensionalityReductionValue");

                    b.Navigation("EmbeddingData");
                });

            modelBuilder.Entity("Domain.Entities.ExternalData.ExternalObject", b =>
                {
                    b.HasOne("Domain.Entities.Embeddings.EmbeddingData", "EmbeddingData")
                        .WithOne("ExternalObject")
                        .HasForeignKey("Domain.Entities.ExternalData.ExternalObject", "EmbeddingDataId");

                    b.Navigation("EmbeddingData");
                });

            modelBuilder.Entity("Domain.Entities.Tasks.MyTask", b =>
                {
                    b.HasOne("Domain.Entities.Tasks.MyTaskState", "State")
                        .WithMany("Tasks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Channel", b =>
                {
                    b.HasOne("Domain.Entities.Customers.Customer", "Loader")
                        .WithMany("Channels")
                        .HasForeignKey("LoaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loader");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Comment", b =>
                {
                    b.HasOne("Domain.Entities.Youtube.Channel", "Channel")
                        .WithMany("Comments")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers.Customer", "Loader")
                        .WithMany("Comments")
                        .HasForeignKey("LoaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Youtube.Video", "Video")
                        .WithMany("Comments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Loader");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Video", b =>
                {
                    b.HasOne("Domain.Entities.Youtube.Channel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Customers.Customer", "Loader")
                        .WithMany("Videos")
                        .HasForeignKey("LoaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Loader");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.ClusterizationAbstactAlgorithm", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Algorithms.ClusterizationAlgorithmType", b =>
                {
                    b.Navigation("ClusterizationAlgorithms");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.Cluster", b =>
                {
                    b.Navigation("ChildClusters");

                    b.Navigation("DisplayedPoints");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationDimensionType", b =>
                {
                    b.Navigation("DimensionValues");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationEntity", b =>
                {
                    b.Navigation("DimensionalityReductionValues");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationProfile", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Tiles");

                    b.Navigation("TilesLevels");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTile", b =>
                {
                    b.Navigation("ChildTiles");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationTilesLevel", b =>
                {
                    b.Navigation("Tiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationType", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspace", b =>
                {
                    b.Navigation("ClusterizationWorkspaceDRTechniques");

                    b.Navigation("Entities");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.Clusterization.ClusterizationWorkspaceDRTechnique", b =>
                {
                    b.Navigation("DRValues");
                });

            modelBuilder.Entity("Domain.Entities.Customers.Customer", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Comments");

                    b.Navigation("Profiles");

                    b.Navigation("Videos");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Domain.Entities.DimensionalityReduction.DimensionalityReductionTechnique", b =>
                {
                    b.Navigation("ClusterizationWorkspaceDRTechniques");

                    b.Navigation("Profiles");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Domain.Entities.DimensionalityReduction.DimensionalityReductionValue", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Domain.Entities.Embeddings.EmbeddingData", b =>
                {
                    b.Navigation("DimensionalityReductionValue")
                        .IsRequired();

                    b.Navigation("Entities");

                    b.Navigation("ExternalObject");

                    b.Navigation("OriginalEmbedding")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.ExternalData.ExternalObject", b =>
                {
                    b.Navigation("ClusterizationEntities");
                });

            modelBuilder.Entity("Domain.Entities.Tasks.MyTaskState", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Channel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Comment", b =>
                {
                    b.Navigation("ClusterizationEntities");

                    b.Navigation("EmbeddingData");
                });

            modelBuilder.Entity("Domain.Entities.Youtube.Video", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
