//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Localization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization.Errors.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алгоритм з такими налаштуваннями вже існує.
        /// </summary>
        public static string AlgorithmAlreadyExists {
            get {
                return ResourceManager.GetString("AlgorithmAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вказаний тип не існує.
        /// </summary>
        public static string ClusterizationAlgorithmTypeIdNotExist {
            get {
                return ResourceManager.GetString("ClusterizationAlgorithmTypeIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квоти користувача не знайдені.
        /// </summary>
        public static string CustomerQuotasNotFound {
            get {
                return ResourceManager.GetString("CustomerQuotasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Техніка зменшення розмірності не знайдена.
        /// </summary>
        public static string DRTechniqueNotFound {
            get {
                return ResourceManager.GetString("DRTechniqueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення зменшення розмірності не знайдено.
        /// </summary>
        public static string DRValueNotFound {
            get {
                return ResourceManager.GetString("DRValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сталася помилка при завантажені ембедінгів.
        /// </summary>
        public static string EmbeddingsLoadingError {
            get {
                return ResourceManager.GetString("EmbeddingsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При збереженні файлу виникла помилка.
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схожа задача вже обробляється.
        /// </summary>
        public static string JobIsAlreadyInProcess {
            get {
                return ResourceManager.GetString("JobIsAlreadyInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Схожа задача вже в черзі.
        /// </summary>
        public static string JobIsAlreadyInQueue {
            get {
                return ResourceManager.GetString("JobIsAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не всі дані вбудовані.
        /// </summary>
        public static string NotAllDataEmbedded {
            get {
                return ResourceManager.GetString("NotAllDataEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такий самий профіль уже завантажено.
        /// </summary>
        public static string ProfileAlreadyExist {
            get {
                return ResourceManager.GetString("ProfileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль не знайдено.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пакет квот не знайдено.
        /// </summary>
        public static string QuotasPackNotFound {
            get {
                return ResourceManager.GetString("QuotasPackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не знайдено.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завдання не знайдено.
        /// </summary>
        public static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тайл не знайдено.
        /// </summary>
        public static string TileNotFound {
            get {
                return ResourceManager.GetString("TileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рівень з тайлами не знайдено.
        /// </summary>
        public static string TilesLevelNotFound {
            get {
                return ResourceManager.GetString("TilesLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач із таким email вже існує.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви не зареєстровані, електронна адреса неправильна.
        /// </summary>
        public static string UserBadEmail {
            get {
                return ResourceManager.GetString("UserBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний пароль.
        /// </summary>
        public static string UserBadPassword {
            get {
                return ResourceManager.GetString("UserBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При створенні користувача виникла помилка.
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я користувача не підходить.
        /// </summary>
        public static string UserNameNotValid {
            get {
                return ResourceManager.GetString("UserNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач не зарєєстрований.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувача не знайдено.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робоча область не знайдена.
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так при додаванні ютуб каналу.
        /// </summary>
        public static string YoutubeChannelAddingError {
            get {
                return ResourceManager.GetString("YoutubeChannelAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб канал вже завантажено.
        /// </summary>
        public static string YoutubeChannelAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeChannelAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб канал не існує.
        /// </summary>
        public static string YoutubeChannelDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeChannelDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так при завантаженні ютуб каналу.
        /// </summary>
        public static string YoutubeChannelLoadingError {
            get {
                return ResourceManager.GetString("YoutubeChannelLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб канал не знайдено.
        /// </summary>
        public static string YoutubeChannelNotFound {
            get {
                return ResourceManager.GetString("YoutubeChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб коментар не знайдено.
        /// </summary>
        public static string YoutubeCommentNotFound {
            get {
                return ResourceManager.GetString("YoutubeCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так при додаванні відео.
        /// </summary>
        public static string YoutubeVideoAddingError {
            get {
                return ResourceManager.GetString("YoutubeVideoAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб відео вже завантажено.
        /// </summary>
        public static string YoutubeVideoAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeVideoAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб відео не існує.
        /// </summary>
        public static string YoutubeVideoDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeVideoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щось пішло не так при завантаженні відео.
        /// </summary>
        public static string YoutubeVideolLoadingError {
            get {
                return ResourceManager.GetString("YoutubeVideolLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ютуб відео не знайдено.
        /// </summary>
        public static string YoutubeVideoNotFound {
            get {
                return ResourceManager.GetString("YoutubeVideoNotFound", resourceCulture);
            }
        }
    }
}
