//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Localization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagePatterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagePatterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization.Errors.ErrorMessagePatterns", typeof(ErrorMessagePatterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlgorithmAlreadyExists.
        /// </summary>
        public static string AlgorithmAlreadyExists {
            get {
                return ResourceManager.GetString("AlgorithmAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationAlgorithmTypeIdNotExist.
        /// </summary>
        public static string ClusterizationAlgorithmTypeIdNotExist {
            get {
                return ResourceManager.GetString("ClusterizationAlgorithmTypeIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerQuotasNotFound.
        /// </summary>
        public static string CustomerQuotasNotFound {
            get {
                return ResourceManager.GetString("CustomerQuotasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayedPointNotFound.
        /// </summary>
        public static string DisplayedPointNotFound {
            get {
                return ResourceManager.GetString("DisplayedPointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRTechniqueNotFound.
        /// </summary>
        public static string DRTechniqueNotFound {
            get {
                return ResourceManager.GetString("DRTechniqueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRValueNotFound.
        /// </summary>
        public static string DRValueNotFound {
            get {
                return ResourceManager.GetString("DRValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailConfirmationError.
        /// </summary>
        public static string EmailConfirmationError {
            get {
                return ResourceManager.GetString("EmailConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailIsAlreadyConfirmed.
        /// </summary>
        public static string EmailIsAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailIsAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSendingToFast.
        /// </summary>
        public static string EmailSendingToFast {
            get {
                return ResourceManager.GetString("EmailSendingToFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddingModelNotFound.
        /// </summary>
        public static string EmbeddingModelNotFound {
            get {
                return ResourceManager.GetString("EmbeddingModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddingsLoadingError.
        /// </summary>
        public static string EmbeddingsLoadingError {
            get {
                return ResourceManager.GetString("EmbeddingsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorWhileLoadExternalData.
        /// </summary>
        public static string ErrorWhileLoadExternalData {
            get {
                return ResourceManager.GetString("ErrorWhileLoadExternalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalObjectsNotFound.
        /// </summary>
        public static string ExternalObjectsNotFound {
            get {
                return ResourceManager.GetString("ExternalObjectsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExternalObjectsPackVisibleTypeIsOnlyOwner.
        /// </summary>
        public static string ExternalObjectsPackVisibleTypeIsOnlyOwner {
            get {
                return ResourceManager.GetString("ExternalObjectsPackVisibleTypeIsOnlyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastClusteringWorkflowNotFound.
        /// </summary>
        public static string FastClusteringWorkflowNotFound {
            get {
                return ResourceManager.GetString("FastClusteringWorkflowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileError.
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIsAlreadyInProcess.
        /// </summary>
        public static string JobIsAlreadyInProcess {
            get {
                return ResourceManager.GetString("JobIsAlreadyInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIsAlreadyInQueue.
        /// </summary>
        public static string JobIsAlreadyInQueue {
            get {
                return ResourceManager.GetString("JobIsAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadedObjectNotTelegramChannel.
        /// </summary>
        public static string LoadedObjectNotTelegramChannel {
            get {
                return ResourceManager.GetString("LoadedObjectNotTelegramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAllDataEmbedded.
        /// </summary>
        public static string NotAllDataEmbedded {
            get {
                return ResourceManager.GetString("NotAllDataEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAllPacksWereLoaded.
        /// </summary>
        public static string NotAllPacksWereLoaded {
            get {
                return ResourceManager.GetString("NotAllPacksWereLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEnoughQuotas.
        /// </summary>
        public static string NotEnoughQuotas {
            get {
                return ResourceManager.GetString("NotEnoughQuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileAlreadyExist.
        /// </summary>
        public static string ProfileAlreadyExist {
            get {
                return ResourceManager.GetString("ProfileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileChangingTypeIsOnlyOwner.
        /// </summary>
        public static string ProfileChangingTypeIsOnlyOwner {
            get {
                return ResourceManager.GetString("ProfileChangingTypeIsOnlyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileIsInCalculation.
        /// </summary>
        public static string ProfileIsInCalculation {
            get {
                return ResourceManager.GetString("ProfileIsInCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileNotFound.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuotasPackNotFound.
        /// </summary>
        public static string QuotasPackNotFound {
            get {
                return ResourceManager.GetString("QuotasPackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleNotFound.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskNotFound.
        /// </summary>
        public static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramChannelAlreadyLoaded.
        /// </summary>
        public static string TelegramChannelAlreadyLoaded {
            get {
                return ResourceManager.GetString("TelegramChannelAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramChannelNotFound.
        /// </summary>
        public static string TelegramChannelNotFound {
            get {
                return ResourceManager.GetString("TelegramChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramChannelUsernameNotValid.
        /// </summary>
        public static string TelegramChannelUsernameNotValid {
            get {
                return ResourceManager.GetString("TelegramChannelUsernameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramMessageAlreadyLoaded.
        /// </summary>
        public static string TelegramMessageAlreadyLoaded {
            get {
                return ResourceManager.GetString("TelegramMessageAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramMessageLoadingError.
        /// </summary>
        public static string TelegramMessageLoadingError {
            get {
                return ResourceManager.GetString("TelegramMessageLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelegramMessageNotFound.
        /// </summary>
        public static string TelegramMessageNotFound {
            get {
                return ResourceManager.GetString("TelegramMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TileNotFound.
        /// </summary>
        public static string TileNotFound {
            get {
                return ResourceManager.GetString("TileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TilesLevelNotFound.
        /// </summary>
        public static string TilesLevelNotFound {
            get {
                return ResourceManager.GetString("TilesLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAlreadyExists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBadEmail.
        /// </summary>
        public static string UserBadEmail {
            get {
                return ResourceManager.GetString("UserBadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserBadPassword.
        /// </summary>
        public static string UserBadPassword {
            get {
                return ResourceManager.GetString("UserBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreationFailed.
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNameNotValid.
        /// </summary>
        public static string UserNameNotValid {
            get {
                return ResourceManager.GetString("UserNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotAuthorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceChangingTypeIsOnlyOwner.
        /// </summary>
        public static string WorkspaceChangingTypeIsOnlyOwner {
            get {
                return ResourceManager.GetString("WorkspaceChangingTypeIsOnlyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceDataObjectsAddPackNotFound.
        /// </summary>
        public static string WorkspaceDataObjectsAddPackNotFound {
            get {
                return ResourceManager.GetString("WorkspaceDataObjectsAddPackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceNotFound.
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceProfilesInCalculation.
        /// </summary>
        public static string WorkspaceProfilesInCalculation {
            get {
                return ResourceManager.GetString("WorkspaceProfilesInCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceVisibleTypeIsOnlyOwner.
        /// </summary>
        public static string WorkspaceVisibleTypeIsOnlyOwner {
            get {
                return ResourceManager.GetString("WorkspaceVisibleTypeIsOnlyOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelAddingError.
        /// </summary>
        public static string YoutubeChannelAddingError {
            get {
                return ResourceManager.GetString("YoutubeChannelAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelAlreadyLoaded.
        /// </summary>
        public static string YoutubeChannelAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeChannelAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelDoesNotExist.
        /// </summary>
        public static string YoutubeChannelDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeChannelDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelLoadingError.
        /// </summary>
        public static string YoutubeChannelLoadingError {
            get {
                return ResourceManager.GetString("YoutubeChannelLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelNotFound.
        /// </summary>
        public static string YoutubeChannelNotFound {
            get {
                return ResourceManager.GetString("YoutubeChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeCommentNotFound.
        /// </summary>
        public static string YoutubeCommentNotFound {
            get {
                return ResourceManager.GetString("YoutubeCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoAddingError.
        /// </summary>
        public static string YoutubeVideoAddingError {
            get {
                return ResourceManager.GetString("YoutubeVideoAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoAlreadyLoaded.
        /// </summary>
        public static string YoutubeVideoAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeVideoAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoDoesNotExist.
        /// </summary>
        public static string YoutubeVideoDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeVideoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideolLoadingError.
        /// </summary>
        public static string YoutubeVideolLoadingError {
            get {
                return ResourceManager.GetString("YoutubeVideolLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoNotFound.
        /// </summary>
        public static string YoutubeVideoNotFound {
            get {
                return ResourceManager.GetString("YoutubeVideoNotFound", resourceCulture);
            }
        }
    }
}
