//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Localization.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagePatterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagePatterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Localization.Errors.ErrorMessagePatterns", typeof(ErrorMessagePatterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlgorithmAlreadyExists.
        /// </summary>
        public static string AlgorithmAlreadyExists {
            get {
                return ResourceManager.GetString("AlgorithmAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClusterizationAlgorithmTypeIdNotExist.
        /// </summary>
        public static string ClusterizationAlgorithmTypeIdNotExist {
            get {
                return ResourceManager.GetString("ClusterizationAlgorithmTypeIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmbeddingsLoadingError.
        /// </summary>
        public static string EmbeddingsLoadingError {
            get {
                return ResourceManager.GetString("EmbeddingsLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIsAlreadyInProcess.
        /// </summary>
        public static string JobIsAlreadyInProcess {
            get {
                return ResourceManager.GetString("JobIsAlreadyInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobIsAlreadyInQueue.
        /// </summary>
        public static string JobIsAlreadyInQueue {
            get {
                return ResourceManager.GetString("JobIsAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskNotFound.
        /// </summary>
        public static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkspaceNotFound.
        /// </summary>
        public static string WorkspaceNotFound {
            get {
                return ResourceManager.GetString("WorkspaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelAddingError.
        /// </summary>
        public static string YoutubeChannelAddingError {
            get {
                return ResourceManager.GetString("YoutubeChannelAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelAlreadyLoaded.
        /// </summary>
        public static string YoutubeChannelAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeChannelAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelDoesNotExist.
        /// </summary>
        public static string YoutubeChannelDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeChannelDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelLoadingError.
        /// </summary>
        public static string YoutubeChannelLoadingError {
            get {
                return ResourceManager.GetString("YoutubeChannelLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeChannelNotFound.
        /// </summary>
        public static string YoutubeChannelNotFound {
            get {
                return ResourceManager.GetString("YoutubeChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeCommentNotFound.
        /// </summary>
        public static string YoutubeCommentNotFound {
            get {
                return ResourceManager.GetString("YoutubeCommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoAddingError.
        /// </summary>
        public static string YoutubeVideoAddingError {
            get {
                return ResourceManager.GetString("YoutubeVideoAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoAlreadyLoaded.
        /// </summary>
        public static string YoutubeVideoAlreadyLoaded {
            get {
                return ResourceManager.GetString("YoutubeVideoAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoDoesNotExist.
        /// </summary>
        public static string YoutubeVideoDoesNotExist {
            get {
                return ResourceManager.GetString("YoutubeVideoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideolLoadingError.
        /// </summary>
        public static string YoutubeVideolLoadingError {
            get {
                return ResourceManager.GetString("YoutubeVideolLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoutubeVideoNotFound.
        /// </summary>
        public static string YoutubeVideoNotFound {
            get {
                return ResourceManager.GetString("YoutubeVideoNotFound", resourceCulture);
            }
        }
    }
}
