//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Types.DataSources.Telegram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelegramChannelFilterTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelegramChannelFilterTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Types.DataSources.Telegram.TelegramChannelFilterTypes", typeof(TelegramChannelFilterTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByLoadedMessageCountDesc.
        /// </summary>
        public static string ByLoadedMessageCountDesc {
            get {
                return ResourceManager.GetString("ByLoadedMessageCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByLoadedMessageCountInc.
        /// </summary>
        public static string ByLoadedMessageCountInc {
            get {
                return ResourceManager.GetString("ByLoadedMessageCountInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByParticipantsDesc.
        /// </summary>
        public static string ByParticipantsDesc {
            get {
                return ResourceManager.GetString("ByParticipantsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByParticipantsInc.
        /// </summary>
        public static string ByParticipantsInc {
            get {
                return ResourceManager.GetString("ByParticipantsInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByTimeDesc.
        /// </summary>
        public static string ByTimeDesc {
            get {
                return ResourceManager.GetString("ByTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ByTimeInc.
        /// </summary>
        public static string ByTimeInc {
            get {
                return ResourceManager.GetString("ByTimeInc", resourceCulture);
            }
        }
    }
}
