//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Types {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DimensionalityReductionTechniques {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DimensionalityReductionTechniques() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Types.DimensionalityReductionTechniques", typeof(DimensionalityReductionTechniques).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isomap.
        /// </summary>
        public static string Isomap {
            get {
                return ResourceManager.GetString("Isomap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSL.
        /// </summary>
        public static string JSL {
            get {
                return ResourceManager.GetString("JSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDA.
        /// </summary>
        public static string LDA {
            get {
                return ResourceManager.GetString("LDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLE.
        /// </summary>
        public static string LLE {
            get {
                return ResourceManager.GetString("LLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDS.
        /// </summary>
        public static string MDS {
            get {
                return ResourceManager.GetString("MDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCA.
        /// </summary>
        public static string PCA {
            get {
                return ResourceManager.GetString("PCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t-SNE.
        /// </summary>
        public static string t_SNE {
            get {
                return ResourceManager.GetString("t-SNE", resourceCulture);
            }
        }
    }
}
