//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources.Types {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuotasTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuotasTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Types.QuotasTypes", typeof(QuotasTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustering.
        /// </summary>
        public static string Clustering {
            get {
                return ResourceManager.GetString("Clustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeddings.
        /// </summary>
        public static string Embeddings {
            get {
                return ResourceManager.GetString("Embeddings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateProfiles.
        /// </summary>
        public static string PrivateProfiles {
            get {
                return ResourceManager.GetString("PrivateProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateWorkspaces.
        /// </summary>
        public static string PrivateWorkspaces {
            get {
                return ResourceManager.GetString("PrivateWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicProfiles.
        /// </summary>
        public static string PublicProfiles {
            get {
                return ResourceManager.GetString("PublicProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicWorkspaces.
        /// </summary>
        public static string PublicWorkspaces {
            get {
                return ResourceManager.GetString("PublicWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
    }
}
